;; -*- mode: eask; lexical-binding: t -*-

(defconst version "0.1.0")

(package "soar-mode"
         version
         "A Major Mode for Soar Agent files")

(website-url "https://github.com/jgrey4296/soar-mode")
(keywords )

(package-file "soar-mode.el")
(files "soar-*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "30.2")
(depends-on "dash")
